# Generated by Django 4.2 on 2023-05-11 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
